//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2014, Open Systems, Inc.
//Wednesday, October 01, 2014
//**************************************
//DO NOT edit this file. Instead use the partial class in PartnerItemXrefProvider.cs
#region Using directives
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Data;
using TRAVERSE.Core;
#endregion

//namespace TRAVERSE.Business
namespace TRAVERSE.Business.PartnerItemXref
{
    /// <summary>
    /// Base class for PartnerItemXrefProvider.
    /// </summary>
    [Serializable]
    public abstract class PartnerItemXrefProviderBase<T> : EntityProviderBase<T>
        where T : PartnerItemXref, new()
    {
        private static IDataProvider _dataProvider = null;
        
        protected override IDataProvider DataProvider
        {
            get
            {
                initDataProvider();
                return _dataProvider;
            }
            set
            {
                base.DataProvider = value;
            }
        }

        #region Helper
        private static void initDataProvider()
        {
            if (_dataProvider == null)
                _dataProvider = DataProviderLoader.Load("TRAVERSE.Data.PartnerItemXref", "PartnerItemXrefDataProvider");
        }
        #endregion "Helper"
        
        #region Fill
        protected override void Fill(IDataReader reader, int start, int pageLength)
        {
            // advance to the starting row
            for (int i = 0; i < start; i++)
            {
                if (!reader.Read())
                    return; // not enough rows, just return
            }
            
            this.Items.RaiseListChangedEvents = false;
            for (int i = 0; i < pageLength; i++)
            {
                if (!reader.Read())
                    break; // we are done
            
                T c = new T();
                c.CompId = this.CompId;
                this.Items.Add(c);
            
                if (c.EntityState == EntityState.Added)
                {
                    c.SuppressEntityEvents = true;
                    c.PartnerId = (System.String)reader["PartnerId"];
                    c.OriginalPartnerId = c.PartnerId;
                    c.TravItemId = (System.String)reader["TravItemId"];
                    c.OriginalTravItemId = c.TravItemId;
                    c.TravUom = (System.String)reader["TravUom"];
                    c.OriginalTravUom = c.TravUom;
                    c.EdiUom = (System.String)reader["EdiUom"];
                    c.EAN = (reader.IsDBNull(reader.GetOrdinal("EAN")))?null:(System.String)reader["EAN"];
                    c.GTIN = (reader.IsDBNull(reader.GetOrdinal("GTIN")))?null:(System.String)reader["GTIN"];
                    c.UPC = (reader.IsDBNull(reader.GetOrdinal("UPC")))?null:(System.String)reader["UPC"];
                    c.SKU = (reader.IsDBNull(reader.GetOrdinal("SKU")))?null:(System.String)reader["SKU"];
                    c.BuyerCode = (reader.IsDBNull(reader.GetOrdinal("BuyerCode")))?null:(System.String)reader["BuyerCode"];
                    c.VendorCode = (reader.IsDBNull(reader.GetOrdinal("VendorCode")))?null:(System.String)reader["VendorCode"];
                    c.InternalCode = (reader.IsDBNull(reader.GetOrdinal("InternalCode")))?null:(System.String)reader["InternalCode"];
                    c.InternalCode1 = (reader.IsDBNull(reader.GetOrdinal("InternalCode1")))?null:(System.String)reader["InternalCode1"];
                    c.InternalCode2 = (reader.IsDBNull(reader.GetOrdinal("InternalCode2")))?null:(System.String)reader["InternalCode2"];
                    this.FillCustom(reader, i);
                    c.AcceptChanges();
                    c.SuppressEntityEvents = false;
                }
                c.ParentCollection = this.Items;
            }
            this.Items.RaiseListChangedEvents = true;
            return;
        }
        #endregion "Fill"
    }
}
