//**************************************
//File generated by TRAVERSE SDK::Code Generator tool.
//Copyright(c) 2014, Open Systems, Inc.
//Friday, October 24, 2014
//**************************************
#region Using directives
using System;
using System.ComponentModel;		
#endregion
namespace TRAVERSE.Business.WebContribImp
{
	///<summary>
	///The data structure representation of the 'tblArWebContribImp_CSI' table.
	///</summary>
	///<remarks>
	///This struct is generated by a tool and should never be modified.
	///</remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal class WebContribImp_CSIEntityData : ICloneable
	{
		#region Variable Declarations
		
		#region Primary key(s)
			/// <summary>			
			/// id : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "tblArWebContribImp_CSI"</remarks>
			public System.Int64 Id;
				
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// TransId : 
		/// </summary>
		public System.String  TransId ;
		
		/// <summary>
		/// PmtDate : 
		/// </summary>
		public System.DateTime?  PmtDate = null;
		
		/// <summary>
		/// PmtAmt : 
		/// </summary>
		public System.Decimal  PmtAmt ;
		
		/// <summary>
		/// CheckNum : 
		/// </summary>
		public System.String  CheckNum = null;
		
		/// <summary>
		/// GroupId : 
		/// </summary>
		public System.String  GroupId = null;
		
		/// <summary>
		/// PmtMethodId : 
		/// </summary>
		public System.String  PmtMethodId = null;
		
		/// <summary>
		/// CcHolder : 
		/// </summary>
		public System.String  CcHolder = null;
		
		/// <summary>
		/// CcNum : 
		/// </summary>
		public System.String  CcNum = null;
		
		/// <summary>
		/// CcExpire : 
		/// </summary>
		public System.DateTime?  CcExpire = null;
		
		/// <summary>
		/// CcAuth : 
		/// </summary>
		public System.String  CcAuth = null;
		
		/// <summary>
		/// CurrencyID : 
		/// </summary>
		public System.String  CurrencyId = null;
		
		/// <summary>
		/// ExchRate : 
		/// </summary>
		public System.Decimal  ExchRate ;
		
		/// <summary>
		/// SourceCode : 
		/// </summary>
		public System.String  SourceCode = null;
		
		/// <summary>
		/// Area : 
		/// </summary>
		public System.String  Area = null;
		
		/// <summary>
		/// CustName : 
		/// </summary>
		public System.String  CustName = null;
		
		/// <summary>
		/// Addr1 : 
		/// </summary>
		public System.String  Addr1 = null;
		
		/// <summary>
		/// Addr2 : 
		/// </summary>
		public System.String  Addr2 = null;
		
		/// <summary>
		/// City : 
		/// </summary>
		public System.String  City = null;
		
		/// <summary>
		/// Region : 
		/// </summary>
		public System.String  Region = null;
		
		/// <summary>
		/// Country : 
		/// </summary>
		public System.String  Country = null;
		
		/// <summary>
		/// PostalCode : 
		/// </summary>
		public System.String  PostalCode = null;
		
		/// <summary>
		/// spAcknowlgmnt : 
		/// </summary>
		public System.String  SpAcknowlgmnt = null;
		
		/// <summary>
		/// Lang : 
		/// </summary>
		public System.String  Lang = null;
		
		/// <summary>
		/// DntSendAcknYN : 
		/// </summary>
		public System.Boolean  DntSendAcknYN ;
		
		/// <summary>
		/// RptExchRate : 
		/// </summary>
		public System.Decimal  RptExchRate ;
		
		/// <summary>
		/// EmailAddr : 
		/// </summary>
		public System.String  EmailAddr = null;
		
		/// <summary>
		/// SendEmailYN : 
		/// </summary>
		public System.Boolean  SendEmailYN ;
		
		/// <summary>
		/// ValidYN : 
		/// </summary>
		public System.Boolean  ValidYN ;
		
		/// <summary>
		/// ImportedYN : 
		/// </summary>
		public System.Boolean  ImportedYN ;
		
		/// <summary>
		/// TravRcptHeaderID : 
		/// </summary>
		public System.Int32?  TravRcptHeaderId = null;
		
		/// <summary>
		/// WebId : 
		/// </summary>
		public System.Int64  WebId ;
		
		/// <summary>
		/// SkipYN : 
		/// </summary>
		public System.Boolean?  SkipYN = null;
		
		/// <summary>
		/// errdescr : 
		/// </summary>
		public System.String  Errdescr = null;
		
		/// <summary>
		/// GroupCountry : 
		/// </summary>
		public System.String  GroupCountry = null;
		
		/// <summary>
		/// GroupState : 
		/// </summary>
		public System.String  GroupState = null;
		
		/// <summary>
		/// GroupCity : 
		/// </summary>
		public System.String  GroupCity = null;
		
		/// <summary>
		/// GroupName : 
		/// </summary>
		public System.String  GroupName = null;
		
		/// <summary>
		/// BillToAddr1 : 
		/// </summary>
		public System.String  BillToAddr1 = null;
		
		/// <summary>
		/// BillToAddr2 : 
		/// </summary>
		public System.String  BillToAddr2 = null;
		
		/// <summary>
		/// BillToCity : 
		/// </summary>
		public System.String  BillToCity = null;
		
		/// <summary>
		/// BillToRegion : 
		/// </summary>
		public System.String  BillToRegion = null;
		
		/// <summary>
		/// BillToCountry : 
		/// </summary>
		public System.String  BillToCountry = null;
		
		/// <summary>
		/// BillToPostalCode : 
		/// </summary>
		public System.String  BillToPostalCode = null;
		
		/// <summary>
		/// CF : 
		/// </summary>
		public System.String  CF = null;
		#endregion
			
		#endregion "Variable Declarations"
		
		public Object Clone()
		{
			WebContribImp_CSIEntityData _tmp = new WebContribImp_CSIEntityData();
						
			_tmp.Id = this.Id;
			
			_tmp.TransId = this.TransId;
			_tmp.PmtDate = this.PmtDate;
			_tmp.PmtAmt = this.PmtAmt;
			_tmp.CheckNum = this.CheckNum;
			_tmp.GroupId = this.GroupId;
			_tmp.PmtMethodId = this.PmtMethodId;
			_tmp.CcHolder = this.CcHolder;
			_tmp.CcNum = this.CcNum;
			_tmp.CcExpire = this.CcExpire;
			_tmp.CcAuth = this.CcAuth;
			_tmp.CurrencyId = this.CurrencyId;
			_tmp.ExchRate = this.ExchRate;
			_tmp.SourceCode = this.SourceCode;
			_tmp.Area = this.Area;
			_tmp.CustName = this.CustName;
			_tmp.Addr1 = this.Addr1;
			_tmp.Addr2 = this.Addr2;
			_tmp.City = this.City;
			_tmp.Region = this.Region;
			_tmp.Country = this.Country;
			_tmp.PostalCode = this.PostalCode;
			_tmp.SpAcknowlgmnt = this.SpAcknowlgmnt;
			_tmp.Lang = this.Lang;
			_tmp.DntSendAcknYN = this.DntSendAcknYN;
			_tmp.RptExchRate = this.RptExchRate;
			_tmp.EmailAddr = this.EmailAddr;
			_tmp.SendEmailYN = this.SendEmailYN;
			_tmp.ValidYN = this.ValidYN;
			_tmp.ImportedYN = this.ImportedYN;
			_tmp.TravRcptHeaderId = this.TravRcptHeaderId;
			_tmp.WebId = this.WebId;
			_tmp.SkipYN = this.SkipYN;
			_tmp.Errdescr = this.Errdescr;
			_tmp.GroupCountry = this.GroupCountry;
			_tmp.GroupState = this.GroupState;
			_tmp.GroupCity = this.GroupCity;
			_tmp.GroupName = this.GroupName;
			_tmp.BillToAddr1 = this.BillToAddr1;
			_tmp.BillToAddr2 = this.BillToAddr2;
			_tmp.BillToCity = this.BillToCity;
			_tmp.BillToRegion = this.BillToRegion;
			_tmp.BillToCountry = this.BillToCountry;
			_tmp.BillToPostalCode = this.BillToPostalCode;
			_tmp.CF = this.CF;
			
			return _tmp;
		}
		
	}//End struct
}


